// Single source of truth for the landing page copy (en / ko / zh).
// Edit here, then run:  node docs-src/build.mjs
// Fields ending in "Html" may contain inline markup; everything else is plain text.

export const site = {
  base: 'https://philaxis.github.io/mulbit/',
  download: 'https://github.com/philaxis/mulbit/releases/latest/download/mulbit.exe',
  repo: 'https://github.com/philaxis/mulbit',
  releases: 'https://github.com/philaxis/mulbit/releases',
  license: 'https://github.com/philaxis/mulbit/blob/main/LICENSE.md',
  email: 'philaxis.dev@gmail.com',
  lastmod: '2026-10-07',
};

// Order = order of the language switcher.
export const langs = {
  en: {
    path: '',
    htmlLang: 'en',
    hreflang: 'en',
    ogLocale: 'en_US',
    label: 'English',
    title: 'mulbit — Free voice typing keyboard for Windows (speech to text at your cursor)',
    description:
      'mulbit is a free voice typing keyboard for Windows. Hold one key, speak, and your words are typed at the cursor in any app. No sign-up, no payment, works offline on your PC.',
    keywords:
      'voice typing, voice keyboard, speech to text, dictation software, free dictation, Windows voice typing, offline speech recognition, Whisper, Gemini',
    ogAlt: 'mulbit, a free voice typing keyboard for Windows: hold G, speak, and the text is typed at your cursor.',
    langNav: 'Language',
    h1Html: '<em>Free</em> voice typing keyboard for Windows',
    lead: 'Speak, and it types at your cursor. One key to start, one key to stop.',
    cta: 'Download for Windows — free',
    ctaSub: 'One file. No installer, no account, no payment.',
    ctaMeta: 'Windows 10 and 11',
    // Each loop of the hero demo plays the next moment; triggers alternate key / mouse.
    // kind picks the mock app layout (mail form, chat thread, assistant prompt, checklist).
    // Keep sentences short: at most two lines in the floating window at phone width.
    demo: {
      moments: [
        { trigger: 'key', kind: 'mail', title: 'New message', toLabel: 'To', to: 'Jun Park', subjectLabel: 'Subject', subject: 'Thursday meeting', greeting: 'Hi Jun,', send: 'Send', words: ['The', 'meeting', 'moved', 'to', 'three.', "I'll", 'send', 'the', 'draft', 'tonight.'] },
        { trigger: 'mouse', kind: 'chat', name: 'Mina', initial: 'M', incoming: 'Still on for seven?', words: ['Yes,', 'see', 'you', 'at', 'the', 'station', 'at', 'seven.'] },
        { trigger: 'key', kind: 'ai', title: 'AI assistant', answer: 'Here is the upload handler.', words: ['Add', 'a', 'retry', 'to', 'the', 'upload', 'API', 'and', 'write', 'a', 'unit', 'test.'] },
        { trigger: 'mouse', kind: 'notes', title: 'Notes', heading: 'To do', date: '7 October', items: ['Send the invoice', 'Book train tickets'], words: ['Renew', 'the', 'passport', 'and', 'call', 'the', 'dentist', 'by', 'Friday.'] },
      ],
      joiner: ' ',
      keyStepsHtml: ['Hold <kbd>G</kbd>', 'Speak', 'Hold <kbd>G</kbd> again'],
      mouseStepsHtml: ['Press a mouse button', 'Speak', 'Press again'],
      result: 'Your words are typed at the cursor.',
      mouseNote: 'Bind mulbit’s shortcut to a spare mouse button in your mouse software and you can dictate with one hand.',
      pause: 'Pause',
      play: 'Play',
      pauseLabel: 'Pause the demonstration',
      playLabel: 'Play the demonstration',
    },
    scenesTitle: 'Where speaking is faster than typing',
    scenes: [
      {
        title: 'Explaining a task to an AI',
        text: 'Say the long prompt to your AI or coding tool out loud instead of typing it.',
        vis: { prompt: 'Refactor the upload handler so a failed chunk retries three times, then shows the error in the status bar and keeps' },
      },
      {
        title: 'Replying in a messenger',
        text: 'Chat windows, documents, browsers: when you stop, the text goes in at the cursor.',
        vis: { incoming: 'Still on for seven?', outgoing: 'Yes, see you at the station at seven.' },
      },
      {
        title: 'Meeting notes and passing thoughts',
        text: 'Transcripts are saved as Markdown files by date, ready to open in Obsidian.',
        vis: { folder: 'Documents\\mulbit', today: 'today' },
      },
    ],
    trustTitle: 'Why it costs nothing to try',
    trust: [
      { title: 'Free', text: 'No sign-up, no subscription, no trial that runs out.' },
      { title: 'Runs on your PC, offline', text: 'Speech recognition runs on your own computer, so your voice never leaves it.' },
      { title: 'No account', text: 'One portable file. Download it and run it.' },
    ],
    startTitle: 'How to start',
    startHtml: [
      'Download <b>mulbit.exe</b> and run it.',
      'Follow the short first-run guide and check your microphone.',
      'Choose on-device recognition (downloads a speech model once, about 250 MB or 1.1 GB) or enter a Gemini API key.',
      'Hold <kbd>G</kbd>, speak, hold <kbd>G</kbd> again. Your words are pasted at the cursor.',
    ],
    faqTitle: 'Questions',
    faq: [
      ['Is mulbit really free?', 'Yes. mulbit is freeware: free to download and use, with no account and no payment.'],
      ['Does it work offline?', 'Yes. With on-device recognition nothing is sent anywhere after the speech model has been downloaded once.'],
      ['Which Windows versions are supported?', 'Windows 10 and 11. Untested preview builds for macOS and Linux are on the releases page.'],
      ['Windows says the app is unrecognised.', 'The app is not code-signed yet. Choose “More info”, then “Run anyway”.'],
      ['Which languages can I dictate in?', 'Korean, English and Chinese are the focus, including mixed speech. The on-device model also understands many other languages.'],
      ['Do I have to use the G key?', 'No. You can bind the shortcut to a spare mouse button, or start and stop by saying a word you have enrolled yourself. A short press of G still types g.'],
      ['Where does the text go?', 'While you speak, the words appear in a small window that stays on top. When you stop, they are pasted at the cursor of the app you are in, and the transcript is saved as a Markdown file by date.'],
      ['Can it be more accurate?', 'Add your own Google Gemini API key for cloud recognition, or try it for 10 seconds without a key.'],
    ],
    endTitle: 'Say it instead of typing it.',
    footNote: 'Free to use. Redistribution and modification are not allowed.',
    footLinks: { github: 'GitHub', releases: 'All releases', privacy: 'Privacy Policy', terms: 'Terms' },
  },

  ko: {
    path: 'ko/',
    htmlLang: 'ko',
    hreflang: 'ko',
    ogLocale: 'ko_KR',
    label: '한국어',
    title: '물빛(mulbit) — 무료 음성 인식 키보드 · 말하면 커서 자리에 써지는 윈도우 받아쓰기',
    description:
      '물빛(mulbit)은 무료 음성 인식 키보드입니다. 키 하나를 딸깍 누르고 말하면 어느 프로그램에서든 커서 자리에 글이 써집니다. 가입도 결제도 없고, 인터넷 없이 내 PC에서 받아씁니다.',
    keywords:
      '음성 인식 키보드, 음성 타이핑, 받아쓰기 프로그램, 무료 받아쓰기, 말로 타이핑, 음성 입력, 윈도우 음성 인식, STT, 딕테이션, 물빛, mulbit',
    ogAlt: '물빛(mulbit), 무료 음성 인식 키보드. G 키를 길게 누르고 말하면 커서 자리에 글이 써집니다.',
    langNav: '언어',
    h1Html: '<em>무료</em> 음성 인식 키보드, 물빛',
    lead: '말하면, 커서가 있는 자리에 글이 써집니다. 딸깍 한 번으로 켜고, 딸깍 한 번으로 끕니다.',
    cta: 'Windows용 물빛 받기 — 무료',
    ctaSub: '파일 하나. 설치도, 가입도, 결제도 없습니다.',
    ctaMeta: 'Windows 10, 11',
    demo: {
      moments: [
        { trigger: 'key', kind: 'mail', title: '새 메일', toLabel: '받는 사람', to: '박준호', subjectLabel: '제목', subject: '목요일 회의', greeting: '준호 님,', send: '보내기', words: ['회의는', '세', '시로', '옮겼습니다.', '초안은', '저녁에', '보낼게요.'] },
        { trigger: 'mouse', kind: 'chat', name: '민지', initial: '민', incoming: '오늘 7시 맞죠?', words: ['네,', '7시에', '역', '앞에서', '봬요.', '늦으면', '연락할게요.'] },
        { trigger: 'key', kind: 'ai', title: 'AI 도우미', answer: '업로드 처리 코드입니다.', words: ['업로드', 'API에', 'retry', '넣고', 'unit', 'test도', '추가해', '줘.'] },
        { trigger: 'mouse', kind: 'notes', title: '메모', heading: '할 일', date: '10월 7일', items: ['견적서 보내기', '기차표 예매하기'], words: ['금요일까지', '여권', '갱신하고', '치과', '예약하기.'] },
      ],
      joiner: ' ',
      keyStepsHtml: ['<kbd>G</kbd> 길게 누르기', '말하기', '다시 <kbd>G</kbd> 길게 누르기'],
      mouseStepsHtml: ['마우스 버튼 누르기', '말하기', '다시 누르기'],
      result: '커서 자리에 글이 써집니다.',
      mouseNote: '마우스 프로그램에서 남는 버튼에 물빛 단축키를 걸어 두면 한 손으로 받아쓸 수 있습니다.',
      pause: '멈춤',
      play: '재생',
      pauseLabel: '시연 멈춤',
      playLabel: '시연 재생',
    },
    scenesTitle: '말이 타자보다 빠른 순간',
    scenes: [
      {
        title: 'AI에게 길게 설명할 때',
        text: 'AI나 코딩 도구에 넣을 긴 요청을 치지 않고 말로 합니다.',
        vis: { prompt: '업로드 처리 코드를 고쳐서 실패한 조각은 세 번까지 다시 시도하고, 그래도 안 되면 상태 표시줄에 오류를 보여 주고 나머지는' },
      },
      {
        title: '메신저에 답장할 때',
        text: '채팅창, 문서, 브라우저 어디든 멈추는 순간 커서 자리에 글이 들어갑니다.',
        vis: { incoming: '오늘 7시 맞죠?', outgoing: '네, 7시에 역 앞에서 봬요.' },
      },
      {
        title: '회의 메모와 떠오른 생각',
        text: '받아쓴 글은 날짜별 Markdown 파일로 저장되어 Obsidian에서 바로 열립니다.',
        vis: { folder: '문서\\mulbit', today: '오늘' },
      },
    ],
    trustTitle: '부담 없이 써 볼 수 있는 이유',
    trust: [
      { title: '공짜입니다', text: '가입, 구독, 기간 제한이 없습니다.' },
      { title: '내 PC에서 받아씁니다', text: '음성 인식이 내 컴퓨터에서 돌아갑니다. 인터넷이 없어도 되고 목소리가 밖으로 나가지 않습니다.' },
      { title: '계정이 필요 없습니다', text: '파일 하나를 받아서 켜면 끝입니다.' },
    ],
    startTitle: '시작하기',
    startHtml: [
      '<b>mulbit.exe</b>를 받아서 실행합니다.',
      '첫 실행 안내를 따라 마이크를 확인합니다.',
      '“내 PC에서”를 고르면 음성 모델을 한 번 받습니다(약 250MB 또는 1.1GB). Gemini API 키를 넣어도 됩니다.',
      '<kbd>G</kbd>를 길게 누르고 말한 뒤 다시 길게 누르면 커서 자리에 붙습니다.',
    ],
    faqTitle: '자주 묻는 것',
    faq: [
      ['정말 무료인가요?', '네. 물빛은 무료 프로그램입니다. 가입이나 결제 없이 받아서 쓸 수 있습니다.'],
      ['인터넷 없이도 되나요?', '네. “내 PC에서” 받아쓰기는 음성 모델을 한 번 받은 뒤에는 아무것도 밖으로 보내지 않습니다.'],
      ['어떤 Windows에서 되나요?', 'Windows 10과 11입니다. Mac과 Linux용은 실제 기기에서 시험하지 못한 미리보기가 릴리스 페이지에 있습니다.'],
      ['Windows가 실행을 막아요.', '아직 서명이 없는 프로그램이라 처음에 경고가 뜹니다. “추가 정보” → “실행”을 누르세요.'],
      ['타자 대신 쓸 만한가요?', 'AI에게 길게 설명하거나 메신저 답장, 회의 메모처럼 말이 타자보다 빠른 일에 잘 맞습니다.'],
      ['어떤 말을 받아쓰나요?', '한국어, 영어, 중국어와 섞어 말하기를 받아씁니다. 내 PC에서 쓰는 모델은 다른 여러 언어도 알아듣습니다.'],
      ['꼭 G 키를 써야 하나요?', '아니요. 마우스의 남는 버튼에 단축키를 걸거나, 내가 등록한 말 한마디로 켜고 끌 수 있습니다. G를 짧게 누르면 평소처럼 g가 입력됩니다.'],
      ['받아쓴 글은 어디로 가나요?', '말하는 동안에는 항상 위에 떠 있는 작은 창에 글이 보입니다. 멈추면 그때 쓰고 있던 프로그램의 커서 자리에 붙고, 날짜별 Markdown 파일로도 저장됩니다.'],
      ['더 정확하게 받아쓸 수 있나요?', '내 Google Gemini API 키를 넣으면 더 정확한 인식을 쓸 수 있고, 키 없이 10초 동안 체험할 수도 있습니다.'],
    ],
    endTitle: '이제 치지 말고 말하세요.',
    footNote: '무료로 쓸 수 있습니다. 재배포와 수정은 안 됩니다.',
    footLinks: { github: 'GitHub', releases: '모든 릴리스', privacy: '개인정보처리방침', terms: '이용 조건' },
  },

  zh: {
    path: 'zh/',
    htmlLang: 'zh-CN',
    hreflang: 'zh-CN',
    ogLocale: 'zh_CN',
    label: '中文',
    title: 'mulbit — 免费语音输入键盘 · 说话即可在光标处输入文字（Windows 语音转文字）',
    description:
      'mulbit 是一款免费的 Windows 语音输入键盘。按住一个键说话，文字就会输入到任何软件的光标处。无需注册、无需付费，可在本机离线识别。',
    keywords: '语音输入, 语音键盘, 语音转文字, 免费语音输入, 听写软件, Windows 语音输入, 离线语音识别, mulbit',
    ogAlt: 'mulbit，免费的 Windows 语音输入键盘：按住 G 说话，文字输入到光标处。',
    langNav: '语言',
    // .nb spans mark the only places where the headline may wrap
    h1Html: '<span class="nb"><em>免费</em>的语音</span><wbr><span class="nb">输入键盘</span> <span class="nb">mulbit</span>',
    lead: '说出的话，自动输入到光标处。按一下开始，再按一下停止。',
    cta: '下载 Windows 版 mulbit — 免费',
    ctaSub: '只有一个文件。无需安装、注册或付费。',
    ctaMeta: 'Windows 10 / 11',
    demo: {
      moments: [
        { trigger: 'key', kind: 'mail', title: '新邮件', toLabel: '收件人', to: '林俊', subjectLabel: '主题', subject: '周四的会议', greeting: '小林：', send: '发送', words: ['会议', '改到', '三点了，', '初稿', '我', '今晚', '发给你。'] },
        { trigger: 'mouse', kind: 'chat', name: '小美', initial: '美', incoming: '今晚七点见吗？', words: ['好的，', '七点', '地铁站见，', '晚了', '我', '提前说。'] },
        { trigger: 'key', kind: 'ai', title: 'AI 助手', answer: '这是上传处理代码。', words: ['给上传', ' API ', '加上', ' retry，', '再补', '一个', '单元测试。'] },
        { trigger: 'mouse', kind: 'notes', title: '备忘', heading: '待办', date: '10月7日', items: ['发送报价单', '订火车票'], words: ['周五之前', '续签护照，', '再预约', '牙医。'] },
      ],
      joiner: '',
      keyStepsHtml: ['按住 <kbd>G</kbd>', '说话', '再按住 <kbd>G</kbd>'],
      mouseStepsHtml: ['按一下鼠标侧键', '说话', '再按一下'],
      result: '文字输入到光标处。',
      mouseNote: '在鼠标软件里把 mulbit 的快捷键绑定到闲置的按键，就可以单手输入。',
      pause: '暂停',
      play: '播放',
      pauseLabel: '暂停演示',
      playLabel: '播放演示',
    },
    scenesTitle: '说比打字更快的时候',
    scenes: [
      {
        title: '向 AI 详细说明需求',
        text: '给 AI 或编程工具的长提示词，不用打字，直接说出来。',
        vis: { prompt: '重构上传处理逻辑，失败的分片最多重试三次，仍然失败就在状态栏显示错误，其余的分片继续' },
      },
      {
        title: '回复聊天消息',
        text: '聊天框、文档、浏览器都可以：停止后文字自动输入到光标所在位置。',
        vis: { incoming: '今晚七点见吗？', outgoing: '好的，七点地铁站见。' },
      },
      {
        title: '会议记录和随时的想法',
        text: '转写内容按日期保存为 Markdown 文件，可直接在 Obsidian 中打开。',
        vis: { folder: '文档\\mulbit', today: '今天' },
      },
    ],
    trustTitle: '可以放心试用的理由',
    trust: [
      { title: '完全免费', text: '没有注册、订阅或试用期限制。' },
      { title: '在本机离线识别', text: '语音识别在你的电脑上运行，无需联网，声音不会离开电脑。在中国大陆也可以使用。' },
      { title: '无需账号', text: '只有一个文件，下载后直接运行。' },
    ],
    startTitle: '开始使用',
    startHtml: [
      '下载 <b>mulbit.exe</b> 并运行。',
      '按照首次引导检查麦克风。',
      '选择“在我的电脑上”会下载一次语音模型（约 250 MB 或 1.1 GB），也可以填写 Gemini API 密钥。',
      '按住 <kbd>G</kbd> 说话，再按住一次，文字就会粘贴到光标处。',
    ],
    faqTitle: '常见问题',
    faq: [
      ['真的免费吗？', '是的。mulbit 是免费软件，无需注册和付费即可下载使用。'],
      ['可以离线使用吗？', '可以。本机识别在下载一次语音模型后，不会向外发送任何内容。'],
      ['支持哪些 Windows 版本？', 'Windows 10 和 11。发布页还有未经实机测试的 macOS 和 Linux 预览版。'],
      ['Windows 阻止运行怎么办？', '应用尚未签名，首次运行会出现提示。点击“更多信息”→“仍要运行”。'],
      ['在中国大陆能用吗？', '可以。选择本机识别即可离线使用；语音模型下载失败时会自动改用镜像站。Gemini 需要能访问 Google 的网络。'],
      ['可以用哪些语言输入？', '支持中文、英语、韩语以及混合语言。本机模型还能识别许多其他语言。'],
      ['一定要用 G 键吗？', '不用。可以把快捷键绑定到闲置的鼠标按钮，也可以用自己录入的口令来开始和停止。短按 G 仍会正常输入 g。'],
      ['转写的文字去哪里了？', '说话时，文字会显示在一个始终置顶的小窗口里。停止后，文字粘贴到当前软件的光标处，同时按日期保存为 Markdown 文件。'],
      ['还能更准确吗？', '填入自己的 Google Gemini API 密钥即可使用云端识别，也可以无密钥体验 10 秒。'],
    ],
    endTitle: '别打字了，直接说。',
    footNote: '免费使用，不允许再分发或修改。',
    footLinks: { github: 'GitHub', releases: '全部版本', privacy: '隐私政策', terms: '使用条款' },
  },
};
